# Generated by Django 3.0 on 2020-07-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_score', models.SmallIntegerField(default=2)),
                ('loser_score', models.SmallIntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('opponents', models.ManyToManyField(related_name='_team_opponents_+', through='record.Record', to='record.Team')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_loser', to='record.Team'),
        ),
        migrations.AddField(
            model_name='record',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='record.Team'),
        ),
    ]
